# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-18 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_record',
            name='job_content',
            field=models.TextField(default='', max_length=100, verbose_name='\u5de5\u4f5c\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='daily_record',
            name='job_plan',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='\u4e0b\u5468\u8ba1\u5212'),
        ),
    ]
