# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-24 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ribao', '0003_auto_20170718_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily_Record',
            new_name='DailyRecord',
        ),
    ]
